# Generated by Django 4.2.2 on 2023-07-02 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_nluimagedata_delete_imagedata"),
    ]

    operations = [
        migrations.RenameModel(old_name="nluImageData", new_name="nluUserData",),
    ]
